---
namespace: kust-dev
replicas:
  - name: appkust-deployment
    count: 1
images:
  - name: marcoliew/my-app
    newName: marcoliew/my-app-pri

resources:
  - ../../../base
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: docker-secret-kust }]


