---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appkust
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: appkust
  template:
    metadata:
      labels:
        app: appkust
    spec:
      containers:
        - name: appkust
          imagePullPolicy: Always
          image: marcoliew/my-app
          ports:
            - containerPort: 80
