apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-lw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-lw
  template:
    metadata:
      labels:
        app: guestbook-lw
    spec:
      containers:
      - images: marcoliew/ks-guestbook-demo
        name: guestbook-lw
        ports:
        - containerPort: 80
