---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appkust-deployment
  labels:
    app: appkust
spec:
  selector:
    matchLabels:
      app: appkust
  template:
    metadata:
      labels:
        app: appkust
    spec:
      containers:
        - name: appkust
          imagePullPolicy: Always
          image: marcoliew/my-app:latest
          ports:
            - containerPort: 80