---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-lw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-lw
  template:
    metadata:
      labels:
        app: guestbook-lw
    spec:
      containers:
        - name: guestbook-lw
          imagePullPolicy: Always
          image: marcoliew/ks-guestbook-demo
          ports:
            - containerPort: 80
